### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by Eomm** [fastify/website-next#20]
We need to implement the index page you can see at:

https://www.fastify.io/

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/11404065/209002993-48a38d96-ecec-440b-a075-3c0e3c7128b4.png">

## Todos

- [x] hero header: I think it is done and working
- [x] organization section
  - [x] add a CSS filter to let the dark theme work
- [x] core features
  - [x] we must check all the links
  - [x] check light/dark theme
- [x] quick start section + Using CLI
- [ ] request/response validation and hooks
- [ ] TypeScript Support
- [x] Buttons sections
- [x] team section
- [x] Acknowledgments section

## Challenges

- [x] Generate the organizations' layout
- [ ] Show some code snippets that switch between async/await **img2
- [x] Generate the team layout

## Tips

- the work of @luisorbaiceta can inspire you at https://github.com/fastify/website-next/blob/3341dd3131a01d7a8e1d3246c8ccb88f1ba9a88b/src/pages/index.tsx

## Open Discussion

- Should we add a switch between CJS/ESM?
- Improve mobile layout (collaborators go from 3 columns to 1 columns instead of 3 -> 2 -> 1)

** img2

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/11404065/209003369-b7b5502f-d5df-44dd-bd2e-529df2f60f09.png">

**Comment by HassanBahati** [comment]
hi @Eomm am up for this issue

**Comment by HassanBahati** [comment]
> ## Open Discussion
> 
>     * Should we add a switch between CJS/ESM?
>

@Eomm i think we should have the switch, so as not to couple ourselves to either.

**Comment by Eomm** [comment]
> i think we should have the switch, so as not to couple ourselves to either.

Right now we have async/await switch so I would replace it for cjs/esm where:

- cjs example has the callback code style
- esm example has the async/await code style

since the snippets are in the index page, we can do it without worrying about the main fastify core repo 👍🏽
